// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// PACKAGETEMPLATETYPE p a c k a g e t e m p l a t e t y p e
// swagger:model PACKAGE_TEMPLATE_TYPE
type PACKAGETEMPLATETYPE string

const (

	// PACKAGETEMPLATETYPERESTSERVICE captures enum value "REST_SERVICE"
	PACKAGETEMPLATETYPERESTSERVICE PACKAGETEMPLATETYPE = "REST_SERVICE"
)

// for schema
var pACKAGETEMPLATETYPEEnum []interface{}

func init() {
	var res []PACKAGETEMPLATETYPE
	if err := json.Unmarshal([]byte(`["REST_SERVICE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		pACKAGETEMPLATETYPEEnum = append(pACKAGETEMPLATETYPEEnum, v)
	}
}

func (m PACKAGETEMPLATETYPE) validatePACKAGETEMPLATETYPEEnum(path, location string, value PACKAGETEMPLATETYPE) error {
	if err := validate.Enum(path, location, value, pACKAGETEMPLATETYPEEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this p a c k a g e t e m p l a t e t y p e
func (m PACKAGETEMPLATETYPE) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validatePACKAGETEMPLATETYPEEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
